### ISSUE TITLE
about the nonlinear IGCV3 block

### ISSUE THREAD

**Issue by Hucley** [homles11/IGCV3#3]
In your  'inverted_residual_unit' ,the activation function of the first group convolution is None,but in the paper(figure 6b), there is a 'relu6' followed by the first group convolution,which is right?

**Comment by sunke123** [comment]
@Hucley . To keep the same count of parameters, our IGCV3 model is twice deeper than MobileNet-V2. Therefore, we remove the first ReLU in IGCV3 block to preserve the count of ReLUs. 
We also discuss about the effect of the position of ReLU.
Welcome to check the details in our paper.

**Comment by Hucley** [comment]
...,IGCV3的论文公开了吗？我只看到了IGCV2的论文，在其中关于IGCV3的细节很少，所以看到你们mx实现和igcv2中图6b不同，所以有了上述疑问...==！还有个疑问，我之前写了个tensorflow版的实现，关于permutation模块，写到最后实现的时候感觉基本和shufflenet的channel_shuffle一致，看了你们mx的对应得实现也差不多，感觉只是分组数的不同...是我理解的这样吗？

**Comment by sunke123** [comment]
@Hucley . We have submitted the paper to Arxiv. You can find it in one or two days. At the implementation stage, permutation is the same as Channel_Shuffle proposed in ShuffleNet, both of which are used to exchange the channels. But, in IGC series works, we propose strict and loose complementary conditions to guide the block design, including the selection of groups for convolutions, which leads to a better performance.

**Comment by Hucley** [comment]
thank you!
