### ISSUE TITLE
confusion about the number of paras in igcv3

### ISSUE THREAD

**Issue by cvtower** [homles11/IGCV3#7]
Hi @homles11 ,

Nice work!
Here i have a question about the implement:
"For IGCV3-D, we reduce the number of blocks to control the count of parameters"-this is mentioned for cifar experiment part. However, no more details ever provided there. While in mobilenet v2 paper, width-multiplier is used to handle the para count.

Width-multiplier is also used in this repo, but i found that pretty low test acc will be return if using 0.5/0.7.

Any mistake here? or do we have to change the training paras for network*0.5/0.7?

Thanks very much for your help!

**Comment by homles11** [comment]
DId you mean the results in Table 2?  This part 0.5 and 0.7 is not width-multiplier, it means the parameter number is about 0.5/0.7 times than IGCV3-D. And we did this by reducing block numbers of each stage.

**Comment by cvtower** [comment]
@homles11 ,

Yes!
In fact igcv3 1.0 result is not so difficult to reproduce(1.0/1.4), but not so much details about the 0.7/0.5 version mentioned within the paper. 

Modify the inverted residual blocks setting:1-4-6-8-6-6-1 need experience, and 1-2-3-4-3-3-1 will produce not so good test acc. I guess repeat time of deeper blocks is limited for less paras version rather than the shallow blocker.  
Since this repo does not include 0.5/0.7 setting, i wonder if you would like to share this info?

Thanks very much for your nice answer!

**Comment by cvtower** [comment]
Hello,

I repeat the training on cifar100 for many times.
My reproduce result : the best acc on cifar100 for 0.5D(same depth as mobilenet v2) model is about 77.10%, most of time 66.5%~ 77.0%, and for 1.0D model the acc mentioned in the paper(77:95~) could be reproduced easily.

Just a report.
Thanks very much for this great work which helps a lot to my study.

**Comment by thinkInJava33** [comment]
i have the same question as yours,1 2 3 4 3 3 1 will not produce the same result as  IGCV3 D-0.5  mentioned in paper @ cvtower hava you solved the problem?
